[4258][FIX] template_content_swapper
qrtl/stx-oca pull request #5
Opened 2024-08-09 08:35 UTC by AungKoKoLin1997

[4258](https://www.quartile.co/web#id=4258&cids=3&menu_id=505&action=1457&model=project.task&view_type=form)

2024-08-09 11:05 UTC, kanda999 requested changes

2024-08-09 11:05 UTC, kanda999 commented on template_content_swapper/models/ir_ui_view.py
>          request = values.get("request")
```suggestion
```

2024-08-13 02:37 UTC, yostashiro reviewed
The scope of `_render_template()` is not clear to me when mega menu is involved.  Is it processed on the mega menu only?  If that is the case, is it still relevant for content swapping at all?

2024-08-13 05:49 UTC, AungKoKoLin1997 commented
> The scope of `_render_template()` is not clear to me when mega menu is involved. Is it processed on the mega menu only? If that is the case, is it still relevant for content swapping at all?

@yostashiro Our scope for content swapping is for all views and reports. So, _render_template() is called every time the view is rendered.

2024-08-13 05:56 UTC, AungKoKoLin1997 commented
I checked the log when I created the mega menu. It seems like the _render_templated is called twice and first one is in cache and there is no values. The first view is `s_mega_menu_odoo_menu` and second view is home page view id.
```
2024-08-13 05:48:15,545 599764 INFO 5rmm3 root: ir.ui.view(1351,) 
2024-08-13 05:48:15,545 599764 INFO 5rmm3 root: None 
2024-08-13 05:48:15,550 599764 INFO 5rmm3 odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2024-08-13 05:48:15,554 599764 INFO 5rmm3 werkzeug: 58.11.156.73 - - [13/Aug/2024 05:48:15] "POST /web/dataset/call_kw/website.menu/save HTTP/1.0" 200 - 95 0.031 0.111
2024-08-13 05:48:16,896 599764 INFO 5rmm3 root: ir.ui.view(1141,) 
2024-08-13 05:48:16,896 599764 INFO 5rmm3 root: {'deletable': True, 'main_object': website.page(4,), 'response_template': 1141, 'request': <odoo.http.HttpRequest object at 0x7f26ba76a070>, 'backend_menu_id': 265}
```

2024-08-13 07:25 UTC, yostashiro commented
@AungKoKoLin1997 My question was more from the business perspective.  Mega menu is totally customizable IIUC, and if that is the case, would there be any point doing the content swapping at all?  If there was no point, I thought one way of handling this case was to just return result if there there was no value.  Not saying that this should be the conclusion.

2024-08-13 07:55 UTC, AungKoKoLin1997 commented
> If there was no point, I thought one way of handling this case was to just return result if there there was no value.

@yostashiro I got the point. When I quick check for other options in website and I see mega menu is only the case. So, I will take your suggestion.

2024-08-13 09:31 UTC, yostashiro commented on template_content_swapper/models/ir_ui_view.py
> +            lang_code = lang_match.group(1)
```.py
        lang_match = re.search(r'data-oe-lang="([^"]+)"', result_str)
        if lang_match:
            # For reports
            lang_code = lang_match.group(1)
```

2024-08-13 09:47 UTC, yostashiro commented on template_content_swapper/models/ir_ui_view.py
> +            lang_code = lang_match.group(1)
Sorry to correct many times...
```.py
        else:
            lang_match = re.search(r'data-oe-lang="([^"]+)"', result_str)
            if lang_match:
                # For reports
                lang_code = lang_match.group(1)
```

2024-08-13 10:04 UTC, yostashiro approved these changes
Code review.

2024-08-14 03:32 UTC, kanda999 approved these changes
Functioanl and Code review.

Could you please update the OCA PR.

2024-08-14 06:32 UTC, merged